CON

  LEFT_MOTOR_SPEED_PIN = 0
  LEFT_MOTOR_CW_PIN = 1
  LEFT_MOTOR_CCW_PIN = 2

  RIGHT_MOTOR_SPEED_PIN = 3
  RIGHT_MOTOR_CW_PIN = 4
  RIGHT_MOTOR_CCW_PIN = 5

  CMUCAM_TX_PIN = 6
  CMUCAM_RX_PIN = 7

  ARM_SERVO_PIN = 8
  ARM_MOTOR_SPEED_PIN = 9
  ARM_MOTOR_CW_PIN = 10
  ARM_MOTOR_CCW_PIN = 11